version: '3.8'

services:
  vite_docker:
    container_name: aggregated-microfrontends-hub-container
    entrypoint: /bin/sh
    image: node:alpine
    volumes:
      - .:/app
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
