version: '3.8'

services:
  app:
    container_name: aggregated-microfrontends-hub-container
    image: aggregated-microfrontends-hub-container
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
